const fizzBuzz = require('./index');

//describe () - declares a test suite (a grouping of tests) | first arg is name & second arg is one or more tests
//it () - declares a test | first arg is name, second arg is a function with the test code
//expect () - creates an assertion. Takes a single arg, typically a value generated by code being tested, returns an obj that exposes matcher functions
//toBe () - a matcher that performs a strict equality test between the value being tested (expect() arg) and expected value (own arg)

describe('fizzBuzz()', ()=> {
    it('returns "FizzBuzz" for multiples of 3 and 5', () => {
        expect(fizzBuzz(15)).toBe('FizzBuzz');
        expect(fizzBuzz(45)).toBe('FizzBuzz');
    });
})