const fizzBuzz = require('./index');

//describe () - declares a test suite (a grouping of tests) | first arg is name & second arg is one or more tests
//it () - declares a test | first arg is name, second arg is a function with the test code
//expect () - creates an assertion. Takes a single arg, typically a value generated by code being tested, returns an obj that exposes matcher functions
//toBe () - a matcher that performs a strict equality test between the value being tested (expect() arg) and expected value (own arg)

describe('fizzBuzz()', () => {
    //passing condition test (first branch of if statement)
    it('should return FizzBuzz if divisible by 3 and 5', () => {
        const fnOutput = fizzBuzz(15);
        expect(fnOutput).toBe('FizzBuzz');
    });

    //failing condition test (second branch of if statement)
    it('should return the input as a string if input is neither a multiple of 3 or 5', () => {
        const outputOne = fizzBuzz(1);
        expect (outputOne).toBe('1');

        const outputTwo = fizzBuzz(22); 
        expect(outputTwo).toBe('22');
        
    })
})